program = {<function>}

function = <name> '(' [<parameter-list>] ')' ':' <type-or-array> <statement>
block-item = <declaration> | <statement>

return = 'return' <expression> ';'
statement = (<return> | <declaration> | <expression> ';') | '{' {<block-item>} '}'

if = 'if' '(' <expression> ')' <statement> {elif} [<else>]
elif = 'elif' '(' <expression> ')' <statement>
else = 'else' <statement>


expression = <assignment> | <conditional-exp>
conditional-exp = <logical-or-exp> ['?' <expression> ':' <expression>]
logical-or-exp = <logical-and-exp> {'||' <logical-and-exp>}
logical-and-exp = <equality-exp> {'&&' <equality-ex>}
equality-exp = <relational-exp> {('==' | '!=') <relational-exp>}
relational-exp = <additive-exp> {('<' | '>' | '<=' | '>=') <additive-exp>}
additive-exp = <term> {('+' | '-') <term>}
term = <factor> {('*' | '/') <factor>}
factor = '(' <expression> ')' | <number> | ('-' | '~' | '!') <factor> | <name>

type-mod = 'const'
type = {<type-mod>} ('int' | 'char')
type-or-array = <type> | '[' <type> ']'

parameter-list = <name> ':' <type-or-array> {',' <variable>}

declaration = <name> ':' <type-or-array> ['=' <expression>] ';'
assignment = <name> '=' <expression>