#include "R-Sharp/NASMCodeGenerator.hpp"
#include "R-Sharp/Logging.hpp"
#include "R-Sharp/AstNodes.hpp"

#include <sstream>

NASMCodeGenerator::NASMCodeGenerator(std::shared_ptr<AstNode> root, std::string R_SharpSource){
    this->root = root;
    this->R_SharpSource = R_SharpSource;
}

void NASMCodeGenerator::indent(){
    indentLevel++;
}
void NASMCodeGenerator::dedent(){
    if (!indentLevel){
        Fatal("Indentation error");
        return;
    }
    indentLevel--;
}
void NASMCodeGenerator::emit(std::string const& str, NASMCodeGenerator::BinarySection section){
    switch (section){
        case NASMCodeGenerator::BinarySection::Text:
            source_text += str;
            break;
        case NASMCodeGenerator::BinarySection::BSS:
            source_bss += str;
            break;
        case NASMCodeGenerator::BinarySection::Data:
            source_data += str;
            break;
    }
}
void NASMCodeGenerator::emitIndented(std::string const& str, NASMCodeGenerator::BinarySection section){
    for (int i=0;i<indentLevel;i++){
        source_text += "    ";
    }
    switch (section){
        case NASMCodeGenerator::BinarySection::Text:
            source_text += str;
            break;
        case NASMCodeGenerator::BinarySection::BSS:
            source_bss += str;
            break;
        case NASMCodeGenerator::BinarySection::Data:
            source_data += str;
            break;
    }
}

std::string NASMCodeGenerator::generate(){
    source_text = "";
    source_data = "";
    source_bss = "";
    indentLevel = 0;
    labelCounter = 0;
    externFunctions = {};
    globalVariables = {};
    root->accept(this);

    // collect the uninitialized global variables
    for (auto& var : globalScope.variables){
        if (!var.initialized){
            emit(var.accessStr.substr(1, var.accessStr.size()-2) + ":\n", BinarySection::BSS);
            switch(var.size){
                case 1: emit("    resb 1\n", BinarySection::BSS); break;
                case 2: emit("    resw 1\n", BinarySection::BSS); break;
                case 4: emit("    resd 1\n", BinarySection::BSS); break;
                case 8: emit("    resq 1\n", BinarySection::BSS); break;
                default: Fatal("Unsupported variable size (" + std::to_string(var.size) + ")");
            }
        }
    }

    std::string output = "";
    output += "; NASM code generated by R-Sharp compiler";
    output += "\n\nBITS 64\n";
    output += "section .text\n";
    output += source_text;
    output += "\nsection .data\n";
    output += source_data;
    output += "\nsection .bss\n";
    output += source_bss;


    return output;
}

void NASMCodeGenerator::emitSyscall(Syscall callNr, std::string const& arg1, std::string const& arg2, std::string const& arg3, std::string const& arg4, std::string const& arg5, std::string const& arg6){
    // move the arguments to rdi, rsi, rdx, r10, r8, and r9 respectively
    emitIndented("; Syscall " + std::to_string(callNr) + "(" + std::to_string(static_cast<int>(callNr)) + ")\n");
    if (arg1 != "") emitIndented("mov rdi, " + arg1 + "\n");
    if (arg2 != "") emitIndented("mov rsi, " + arg2 + "\n");
    if (arg3 != "") emitIndented("mov rdx, " + arg3 + "\n");
    if (arg4 != "") emitIndented("mov r10, " + arg4 + "\n");
    if (arg5 != "") emitIndented("mov r8, " + arg5 + "\n");
    if (arg6 != "") emitIndented("mov r9, " + arg6 + "\n");

    emitIndented("mov rax, " + std::to_string(static_cast<int>(callNr)) + "\n");

    emitIndented("syscall\n");
}

std::string NASMCodeGenerator::getUniqueLabel(std::string const& prefix){
    return prefix + "_" + std::to_string(labelCounter++);
}

NASMCodeGenerator::Variable NASMCodeGenerator::addVariable(AstVariableDeclaration* node){
    Variable var;
    var.name = node->name;
    if (node->type->getType() == AstNodeType::AstBuiltinType)
        var.type = std::static_pointer_cast<AstBuiltinType>(node->type)->name;
    else{
        Error("Only builtin types are supported");
        printErrorToken(node->token);
        exit(1);
    }
    if (var.type == "i64"){
        var.size = 8;
    }
    else if (var.type == "i32"){
        var.size = 4;
    }
    else{
        Fatal("Only i64 and i32 are supported");
    }

    if (node->isGlobal){
        // test if the variable is already declared
        if (std::find(globalScope.variables.begin(), globalScope.variables.end(), var) != globalScope.variables.end()){
            auto match = std::find(globalScope.variables.begin(), globalScope.variables.end(), var);
            if (match->initialized){
                Error("Variable " + var.name + " is already defined");
                printErrorToken(node->token);
                exit(1);
            }
            else{
                match->initialized = true;
                return *match;
            }
        }

        globalVariables.push_back(node->name);
        var.accessStr = "[" + getUniqueLabel(node->name) + "]";
        var.initialized = node->value != nullptr;
        globalScope.variables.push_back(var);
    }
    else{
        stackOffset += var.size;
        var.accessStr = "[rbp - " + std::to_string(stackOffset) + "]";
        getCurrentVariableScope().variables.push_back(var);
    }
    return var;
}
NASMCodeGenerator::Variable NASMCodeGenerator::getVariable(std::string const& name){
    for (auto scope = getCurrentStackFrame().variableScopes.rbegin(); scope != getCurrentStackFrame().variableScopes.rend(); scope++){
        for (auto const& var : scope->variables){
            if (var.name == name) return var;
        }
    }
    // if we didn't find it in the current scope, it must be global
    for (auto const& var : globalScope.variables){
        if (var.name == name) return var;
    }

    Fatal("Variable " + name + " not found");
    return Variable();
}
void NASMCodeGenerator::pushStackFrame(){
    emitIndented("; Create stack frame\n");

    // save callee-saved registers
    emitIndented("push rbx\n");
    emitIndented("push rbp\n");
    emitIndented("push r12\n");
    emitIndented("push r13\n");
    emitIndented("push r14\n");
    emitIndented("push r15\n");
    emitIndented("mov rbp, rsp\n");

    stackFrames.emplace_back();
    stackFrames.back().variableScopes.emplace_back();
    stackOffset = 0;
}
int NASMCodeGenerator::getCurrentScopeSize(){
    return getScopeSize(getCurrentVariableScope());
}
int NASMCodeGenerator::getScopeSize(VariableScope const& scope){
    int size = 0;
    for (auto& var : scope.variables){
        size += var.size;
    }
    return size;
}

void NASMCodeGenerator::popStackFrame(bool codeOnly){
    if (!codeOnly){
        while (getCurrentStackFrame().variableScopes.size()){
            popVariableScope();
        }
    }
    else{
        for (auto varScope = stackFrames.back().variableScopes.rbegin(); varScope != stackFrames.back().variableScopes.rend(); varScope++){
            popVariableScope(*varScope);
        }
    }
    emitIndented("; Destroy stack frame\n");
    
    // restore callee-saved registers
    emitIndented("pop r15\n");
    emitIndented("pop r14\n");
    emitIndented("pop r13\n");
    emitIndented("pop r12\n");
    emitIndented("pop rbp\n");
    emitIndented("pop rbx\n");
    if (!codeOnly)
        stackFrames.pop_back();
}
void NASMCodeGenerator::pushVariableScope(){
    stackFrames.back().variableScopes.emplace_back();
}
void NASMCodeGenerator::popVariableScope(){
    popVariableScope(getCurrentVariableScope());
    stackOffset -= getCurrentScopeSize();
    getCurrentStackFrame().variableScopes.pop_back();
}
void NASMCodeGenerator::popVariableScope(VariableScope const& scope){
    emitIndented("add rsp, " + std::to_string(getScopeSize(scope)) + "\n");
}
NASMCodeGenerator::StackFrame& NASMCodeGenerator::getCurrentStackFrame(){
    return stackFrames.back();
}
NASMCodeGenerator::VariableScope& NASMCodeGenerator::getCurrentVariableScope(){
    return stackFrames.back().variableScopes.back();
}

std::string NASMCodeGenerator::sizeToNASMType(int size){
    if (size == 8) return "qword";
    else if (size == 4) return "dword";
    else if (size == 2) return "word";
    else if (size == 1) return "byte";
    else{
        Fatal("Invalid size ", size);
        return "";
    }
}

// program
void NASMCodeGenerator::visit(AstProgram* node){
    for (auto const& child : node->getChildren()){
        if (child->getType() == AstNodeType::AstFunction || child->getType() == AstNodeType::AstFunctionDeclaration){
            child->accept(this);
        }
        else if (child->getType() == AstNodeType::AstVariableDeclaration){
            child->accept(this);
        }
        else{
            Fatal("Invalid node type in program");
        }
    }

    // emit extern functions
    for (auto const& func : externFunctions){
        emitIndented("extern " + func + "\n");
    }
}
void NASMCodeGenerator::visit(AstParameterList* node){
    int argumentNumber = 0;
    for (auto const& child : node->parameters){
        child->accept(this);
        Variable var = getVariable(child->name);

        emitIndented("; Load argument " + std::to_string(argumentNumber) + "\n");
        emitIndented("mov " + sizeToNASMType(var.size) + " " + var.accessStr + ", ");

        switch(argumentNumber){
            case 0: emit("rdi\n"); break;
            case 1: emit("rsi\n"); break;
            case 2: emit("rdx\n"); break;
            case 3: emit("rcx\n"); break;
            case 4: emit("r8\n"); break;
            case 5: emit("r9\n"); break;
        }

        argumentNumber++;
    }
}

// definitions
void NASMCodeGenerator::visit(AstFunction* node){
    emitIndented("; Function " + node->name + "\n\n");
    emitIndented("global " + node->name + "\n");
    emitIndented(node->name + ":\n");
    indent();
    pushStackFrame();

    node->parameters->accept(this);
    node->body->accept(this);

    popStackFrame();
    emitIndented("mov rax, 0\n");
    emitIndented("ret\n");
    dedent();

    // remove this function from externFunctions
    for (auto it = externFunctions.begin(); it != externFunctions.end(); it++){
        if (*it == node->name){
            externFunctions.erase(it);
            break;
        }
    }
}
void NASMCodeGenerator::visit(AstFunctionDeclaration* node){
    // add function to externFunctions if it is not already there
    if (std::find(externFunctions.begin(), externFunctions.end(), node->name) == externFunctions.end()){
        externFunctions.push_back(node->name);
    }
}


// statements
void NASMCodeGenerator::visit(AstBlock* node){
    pushVariableScope();
    for (auto const& child : node->getChildren()){
        child->accept(this);
    }
    popVariableScope();
}
void NASMCodeGenerator::visit(AstReturn* node){
    node->value->accept(this);
    popStackFrame(true);
    emitIndented("ret\n");
}
void NASMCodeGenerator::visit(AstConditionalStatement* node){
    std::string else_label = getUniqueLabel("else");
    std::string end_label = getUniqueLabel("end");

    node->condition->accept(this);
    emitIndented("; If statement\n");
    emitIndented("cmp rax, 0\n");
    emitIndented("je " + else_label + "\n");
    indent();
    node->trueStatement->accept(this);
    emitIndented("jmp " + end_label + "\n");
    dedent();
    emitIndented(else_label + ":\n");
    indent();
    if (node->falseStatement) node->falseStatement->accept(this);
    dedent();
    emitIndented(end_label + ":\n");
}
void NASMCodeGenerator::visit(AstForLoopDeclaration* node){
    std::string start_label = getUniqueLabel("start");
    std::string end_label = getUniqueLabel("end");
    std::string increment_label = getUniqueLabel("increment");

    getCurrentStackFrame().loopInfo.push_back({increment_label, end_label});

    pushVariableScope();
    getCurrentVariableScope().hasLoop = true;
    
    emitIndented("; For loop\n");
    emitIndented("; Initialization\n");
    node->variable->accept(this);

    emitIndented("; For loop\n");
    emitIndented(start_label + ":\n");
    indent();
    emitIndented("; Condition\n");
    node->condition->accept(this);
    emitIndented("cmp rax, 0\n");
    emitIndented("je " + end_label + "\n");
    emitIndented("; Body\n");
    node->body->accept(this);
    dedent();
    emitIndented("; Increment\n");
    emitIndented(increment_label + ":\n");
    indent();
    node->increment->accept(this);
    emitIndented("jmp " + start_label + "\n");
    dedent();
    emitIndented(end_label + ":\n");

    getCurrentVariableScope().hasLoop = false;
    popVariableScope();

    getCurrentStackFrame().loopInfo.pop_back();
}
void NASMCodeGenerator::visit(AstForLoopExpression* node){
    std::string start_label = getUniqueLabel("start");
    std::string end_label = getUniqueLabel("end");
    std::string increment_label = getUniqueLabel("increment");

    getCurrentStackFrame().loopInfo.push_back({increment_label, end_label});
    getCurrentVariableScope().hasLoop = true;

    emitIndented("; For loop\n");
    emitIndented("; Initialization\n");
    node->variable->accept(this);

    emitIndented("; For loop\n");
    emitIndented(start_label + ":\n");
    indent();
    emitIndented("; Condition\n");
    node->condition->accept(this);
    emitIndented("cmp rax, 0\n");
    emitIndented("je " + end_label + "\n");
    emitIndented("; Body\n");
    node->body->accept(this);
    dedent();
    emitIndented("; Increment\n");
    emitIndented(increment_label + ":\n");
    indent();
    node->increment->accept(this);
    emitIndented("jmp " + start_label + "\n");
    dedent();
    emitIndented(end_label + ":\n");

    getCurrentVariableScope().hasLoop = false;
    getCurrentStackFrame().loopInfo.pop_back();
}
void NASMCodeGenerator::visit(AstWhileLoop* node){
    std::string start_label = getUniqueLabel("start");
    std::string end_label = getUniqueLabel("end");

    getCurrentStackFrame().loopInfo.push_back({start_label, end_label});
    getCurrentVariableScope().hasLoop = true;

    emitIndented("; While loop\n");
    emitIndented(start_label + ":\n");
    indent();
    node->condition->accept(this);
    emitIndented("cmp rax, 0\n");
    emitIndented("je " + end_label + "\n");
    emitIndented("; Body\n");
    node->body->accept(this);
    emitIndented("jmp " + start_label + "\n");
    dedent();
    emitIndented(end_label + ":\n");

    getCurrentVariableScope().hasLoop = false;
    getCurrentStackFrame().loopInfo.pop_back();
}
void NASMCodeGenerator::visit(AstDoWhileLoop* node){
    std::string start_label = getUniqueLabel("start");
    std::string end_label = getUniqueLabel("end");

    getCurrentStackFrame().loopInfo.push_back({start_label, end_label});
    getCurrentVariableScope().hasLoop = true;

    emitIndented("; Do loop\n");
    emitIndented(start_label + ":\n");
    indent();
    emitIndented("; Body\n");
    node->body->accept(this);
    node->condition->accept(this);
    emitIndented("cmp rax, 0\n");
    emitIndented("jne " + start_label + "\n");
    dedent();
    emitIndented(end_label + ":\n");

    getCurrentVariableScope().hasLoop = false;
    getCurrentStackFrame().loopInfo.pop_back();

}
void NASMCodeGenerator::visit(AstBreak* node){
    if (getCurrentStackFrame().loopInfo.empty()){
        Error("NASM Generator: Break statement outside of loop!");
    }

    for (auto varScope = getCurrentStackFrame().variableScopes.rbegin(); varScope != getCurrentStackFrame().variableScopes.rend(); ++varScope){
        if (varScope->hasLoop){
            break;
        }
        else{
            popVariableScope(*varScope);
        }
    }

    emitIndented("; Break\n");
    emitIndented("jmp " + getCurrentStackFrame().loopInfo.back().breakLabel + "\n");
}
void NASMCodeGenerator::visit(AstSkip* node){
    if (getCurrentStackFrame().loopInfo.empty()){
        Error("NASM Generator: Skip statement outside of loop!");
    }
    for (auto varScope = getCurrentStackFrame().variableScopes.rbegin(); varScope != getCurrentStackFrame().variableScopes.rend(); ++varScope){
        if (varScope->hasLoop){
            break;
        }
        else{
            popVariableScope(*varScope);
        }
    }

    emitIndented("; Skip\n");
    emitIndented("jmp " + getCurrentStackFrame().loopInfo.back().skipLabel + "\n");
}


// expressions
void NASMCodeGenerator::visit(AstUnary* node){
    node->value->accept(this);
    switch (node->type){
        case AstUnaryType::Negate:
            emitIndented("neg rax\n");
            break;
        case AstUnaryType::BinaryNot:
            emitIndented("not rax\n");
            break;
        case AstUnaryType::LogicalNot:
            emitIndented("cmp rax, 0\n");
            emitIndented("mov rax, 0\n");
            emitIndented("sete al\n");
            break;
        default:
            Error("NASM Generator: Unary operator not implemented!");
            printErrorToken(node->token);
            exit(1);
            break;
    }
}
void NASMCodeGenerator::visit(AstBinary* node){
    node->left->accept(this);

    // logical and and or will short circuit, so the right side is not evaluated until necessary
    if (!(node->type == AstBinaryType::LogicalAnd || node->type == AstBinaryType::LogicalOr)){
        emitIndented("push rax\n");
        node->right->accept(this);
        emitIndented("mov rbx, rax\n");
        emitIndented("pop rax\n");
    }
    switch (node->type){
        case AstBinaryType::Add:
            emitIndented("; Add\n");
            emitIndented("add rax, rbx\n");
            break;
        case AstBinaryType::Subtract:
            emitIndented("; Subtract\n");
            emitIndented("sub rax, rbx\n");
            break;
        case AstBinaryType::Multiply:
            emitIndented("; Multiply\n");
            emitIndented("imul rax, rbx\n");
            break;
        case AstBinaryType::Divide:
            emitIndented("; Divide\n");
            emitIndented("cqo\n");
            emitIndented("idiv rbx\n");
            break;
        case AstBinaryType::Modulo:
            emitIndented("; Modulo\n");
            emitIndented("cqo\n");
            emitIndented("idiv rbx\n");
            emitIndented("mov rax, rdx\n");
            break;

        case AstBinaryType::Equal:
            emitIndented("; Equal\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("sete al\n");
            break;
        case AstBinaryType::NotEqual:
            emitIndented("; Not Equal\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setne al\n");
            break;
        case AstBinaryType::LessThan:
            emitIndented("; Less Than\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setl al\n");
            break;
        case AstBinaryType::LessThanOrEqual:
            emitIndented("; Less Than Or Equal\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setle al\n");
            break;
        case AstBinaryType::GreaterThan:
            emitIndented("; Greater Than\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setg al\n");
            break;
        case AstBinaryType::GreaterThanOrEqual:
            emitIndented("; Greater Than Or Equal\n");
            emitIndented("cmp rax, rbx\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setge al\n");
            break;

        case AstBinaryType::LogicalAnd:{
            emitIndented("; Logical And\n");
            std::string clause2 = getUniqueLabel("second_expression");
            std::string end = getUniqueLabel("end");
            emitIndented("cmp rax, 0\n");
            emitIndented("jne " + clause2 + "\n");
            emitIndented("jmp " + end + "\n");
            emitIndented(clause2 + ":\n"); indent();

            // evaluate right side
            node->right->accept(this);
            emitIndented("cmp rax, 0\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setne al\n");
            dedent();
            emitIndented(end + ":\n");
            break;
        }

        case AstBinaryType::LogicalOr:{
            emitIndented("; Logical Or\n");
            std::string clause2 = getUniqueLabel("second_expression");
            std::string end = getUniqueLabel("end");
            emitIndented("cmp rax, 0\n");
            emitIndented("je " + clause2 + "\n");
            emitIndented("mov rax, 1\n");
            emitIndented("jmp " + end + "\n");
            emitIndented(clause2 + ":\n"); indent();

            // evaluate right side
            node->right->accept(this);
            emitIndented("cmp rax, 0\n");
            emitIndented("mov rax, 0\n");
            emitIndented("setne al\n");
            dedent();
            emitIndented(end + ":\n");
            break;
        }
        default:
            Error("NASM Generator: Binary operator not implemented!");
            printErrorToken(node->token);
            exit(1);
            break;
    }
}
void NASMCodeGenerator::visit(AstInteger* node){
    emitIndented("; Integer " + std::to_string(node->value) + "\n");
    emitIndented("mov rax, " + std::to_string(node->value) + "\n");
}
void NASMCodeGenerator::visit(AstVariableAccess* node){
    emitIndented("; Variable Access(" + node->name + ")\n");
    Variable var = getVariable(node->name);
    emitIndented("mov " + sizeToNASMType(var.size) + " rax, " + var.accessStr + "\n");
}
void NASMCodeGenerator::visit(AstVariableAssignment* node){
    Variable var = getVariable(node->name);
    node->value->accept(this);
    emitIndented("mov " + sizeToNASMType(var.size) + " " + var.accessStr + ", rax\n");
}
void NASMCodeGenerator::visit(AstConditionalExpression* node){
    std::string true_clause = getUniqueLabel("true_expression");
    std::string false_clause = getUniqueLabel("false_expression");
    std::string end = getUniqueLabel("end");
    node->condition->accept(this);
    emitIndented("; Conditional Expression\n");
    emitIndented("cmp rax, 0\n");
    emitIndented("je " + false_clause + "\n");
    emitIndented(true_clause + ":\n"); indent();
    node->trueExpression->accept(this);
    emitIndented("jmp " + end + "\n");
    dedent();
    emitIndented(false_clause + ":\n"); indent();
    node->falseExpression->accept(this);
    dedent();
    emitIndented(end + ":\n");
}
void NASMCodeGenerator::visit(AstEmptyExpression* node){
    emitIndented("; Empty Expression\n");
    emitIndented("mov rax, 1\n");
}
void NASMCodeGenerator::visit(AstFunctionCall* node){
    // rdi, rsi, rdx, rcx, r8, and r9 are used for parameters
    // more than 6 parameters are not supported yet

    if (node->arguments.size() > 6){
        Error("NASM Generator: More than 6 parameters are not supported yet!");
        printErrorToken(node->token);
        exit(1);
    }
    // save registers
    emitIndented("; Prepare for function call (" + node->name + ")\n");
    int argCount = node->arguments.size();
    for (int i = 0; i < argCount; i++){
        switch(i){
            case 0: emitIndented("push rdi\n"); break;
            case 1: emitIndented("push rsi\n"); break;
            case 2: emitIndented("push rdx\n"); break;
            case 3: emitIndented("push rcx\n"); break;
            case 4: emitIndented("push r8\n"); break;
            case 5: emitIndented("push r9\n"); break;
        }
    }

    // evaluate arguments
    for (auto arg : node->arguments){
        arg->accept(this);
        emitIndented("push rax\n");
    }
    // move arguments to registers
    for (int i = argCount - 1; i >= 0; i--){
        switch(i){
            case 0: emitIndented("pop rdi\n"); break;
            case 1: emitIndented("pop rsi\n"); break;
            case 2: emitIndented("pop rdx\n"); break;
            case 3: emitIndented("pop rcx\n"); break;
            case 4: emitIndented("pop r8\n"); break;
            case 5: emitIndented("pop r9\n"); break;
        }
    }

    emitIndented("; Function Call (" + node->name + ")\n");
    emitIndented("call " + node->name + "\n");

    emitIndented("; Restore after function call (" + node->name + ")\n");
    // restore registers
    for (int i = argCount - 1; i >= 0; i--){
        switch(i){
            case 0: emitIndented("pop rdi\n"); break;
            case 1: emitIndented("pop rsi\n"); break;
            case 2: emitIndented("pop rdx\n"); break;
            case 3: emitIndented("pop rcx\n"); break;
            case 4: emitIndented("pop r8\n"); break;
            case 5: emitIndented("pop r9\n"); break;
        }
    }
}


// declarations
void NASMCodeGenerator::visit(AstVariableDeclaration* node){
    Variable var = addVariable(node);
    if (node->isGlobal){
        if (!node->value){
            return;
        }
        if (node->value->getType() != AstNodeType::AstInteger){
            Error("NASM Generator: Global variable must be of type integer!");
            printErrorToken(node->token);
            exit(1);
        }
        auto intNode = std::static_pointer_cast<AstInteger>(node->value);
        emit("    ; Global Variable (" + node->name + ")\n", BinarySection::Data);
        // remove the brackets from the name
        std::string label = var.accessStr.substr(1, var.accessStr.size()-2);
        emit("    global " + label + "\n", BinarySection::Data);
        emit(label + ":\n", BinarySection::Data);
        switch(var.size){
            case 1: emit("    db " + std::to_string(intNode->value) + "\n", BinarySection::Data); break;
            case 2: emit("    dw " + std::to_string(intNode->value) + "\n", BinarySection::Data); break;
            case 4: emit("    dd " + std::to_string(intNode->value) + "\n", BinarySection::Data); break;
            case 8: emit("    dq " + std::to_string(intNode->value) + "\n", BinarySection::Data); break;
            default:
                Error("NASM Generator: Global variable size not supported!");
                printErrorToken(node->token);
                exit(1);
                break;
        }
    }
    else{
        emitIndented("; Variable (" + node->name + ")\n");
        if (node->value){
            node->value->accept(this);
            emitIndented("push " + sizeToNASMType(var.size) + " rax\n");
        }
        else{
            emitIndented("push " + sizeToNASMType(var.size) + " 0\n");
        }
    }
}


void NASMCodeGenerator::printErrorToken(Token token){
    int start = token.position.startPos;
    int end = token.position.endPos;

    std::string src = R_SharpSource;
    src.replace(start, end - start, "\033[31m" + src.substr(start, end - start) + "\033[0m");

    // print the error and 3 lines above it
    std::stringstream ss;
    int line = 1;
    int column = 1;
    int pos = 0;

    for (char c : src) {
        if (line >= token.position.line - 3 && line <= token.position.line) {
            if (column == 1){
                ss << line << "| ";
            }
            if (line == token.position.line && c == '\n') break;
            ss << c;
        }
        pos++;
        if (c == '\n') {
            line++;
            column = 1;
        } else {
            column++;
        }
    }

    int prefixLen = (std::to_string(token.position.line) + "| ").length();

    ss << "\n\033[31m" // enable red text
        << std::string(prefixLen + token.position.column - 1, ' ') // print spaces before the error
        << "^";
    try {
        ss << std::string(end - start - 1, '~'); // underline the error
    }
    catch(std::length_error){}

    ss << "\033[0m"; // disable red text
    Print(ss.str());
}